### ISSUE TITLE
Sometimes the web crashes

### ISSUE THREAD

**Issue by Lime18** [blaxxun-boop/Webinterface#1]
Console errors
```
PHP Fatal error:  Uncaught Amp\ByteStream\ClosedException: The stream is not writable in /opt/web/vendor/amphp/byte-stream/lib/ResourceOutputStream.php:218
Stack trace:
#0 /opt/web/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(164): Amp\ByteStream\ResourceOutputStream->send()
#1 /opt/web/vendor/amphp/socket/src/ResourceSocket.php(134): Amp\ByteStream\ResourceOutputStream->write()
#2 /opt/web/vendor/amphp/http-server/src/Driver/UpgradedSocket.php(55): Amp\Socket\ResourceSocket->write()
#3 /opt/web/vendor/amphp/websocket/src/Rfc6455Client.php(603): Amp\Http\Server\Driver\UpgradedSocket->write()
#4 /opt/web/vendor/amphp/websocket/src/Rfc6455Client.php(505): Amp\Websocket\Rfc6455Client->write()
#5 /opt/web/vendor/amphp/websocket/src/Rfc6455Client.php(457): Amp\Websocket\Rfc6455Client->sendData()
#6 /opt/web/vendor/amphp/amp/lib/Future.php(137): Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#7 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(744): Amp\Future::Amp\{closure}()
#8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
#9 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(691): Fiber->resume()
#10 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(604): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#11 /opt/web/vendor/revolt/event-loop/src/EventLoop/Driver/StreamSelectDriver.php(123): Revolt\EventLoop\Internal\AbstractDriver->invokeCallback()
#12 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(676): Revolt\EventLoop\Driver\StreamSelectDriver->dispatch()
#13 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Revolt\EventLoop\Internal\AbstractDriver->tick()
#14 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->run()
#15 /opt/web/vendor/revolt/event-loop/src/EventLoop/Suspension.php(95): Fiber->resume()
#16 /opt/web/vendor/amphp/amp/lib/functions.php(81): Revolt\EventLoop\Suspension->suspend()
#17 /opt/web/server.php(346): Amp\trapSignal()
#18 {main}

Next Amp\Websocket\ClosedException: Client unexpectedly closed; Code 1006 (ABNORMAL_CLOSE); Reason: "Writing to the client failed" in /opt/web/vendor/amphp/websocket/src/Rfc6455Client.php:510
Stack trace:
#0 /opt/web/vendor/amphp/amp/lib/Future.php(166): Amp\Websocket\Rfc6455Client->Amp\Websocket\{closure}()
#1 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(744): Amp\Future::Amp\{closure}()
#2 [internal function]: Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
#3 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(691): Fiber->resume()
#4 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(604): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#5 /opt/web/vendor/revolt/event-loop/src/EventLoop/Driver/StreamSelectDriver.php(123): Revolt\EventLoop\Internal\AbstractDriver->invokeCallback()
#6 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(676): Revolt\EventLoop\Driver\StreamSelectDriver->dispatch()
#7 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Revolt\EventLoop\Internal\AbstractDriver->tick()
#8 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->run()
#9 /opt/web/vendor/revolt/event-loop/src/EventLoop/Suspension.php(95): Fiber->resume()
#10 /opt/web/vendor/amphp/amp/lib/functions.php(81): Revolt\EventLoop\Suspension->suspend()
#11 /opt/web/server.php(346): Amp\trapSignal()
#12 {main}

Next Amp\Future\UnhandledFutureError: Unhandled future error: "Client unexpectedly closed; Code 1006 (ABNORMAL_CLOSE); Reason: "Writing to the client failed""; Await the Future with Future::await() before the future is destroyed or use Future::ignore() to suppress this exception in /opt/web/vendor/amphp/amp/lib/Internal/FutureState.php:38
Stack trace:
#0 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(746): Amp\Internal\FutureState->__destruct()
#1 [internal function]: Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
#2 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(744): Fiber->throw()
#3 [internal function]: Revolt\EventLoop\Internal\AbstractDriver::Revolt\EventLoop\Internal\{closure}()
#4 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(691): Fiber->resume()
#5 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(604): Revolt\EventLoop\Internal\AbstractDriver->invokeMicrotasks()
#6 /opt/web/vendor/revolt/event-loop/src/EventLoop/Driver/StreamSelectDriver.php(123): Revolt\EventLoop\Internal\AbstractDriver->invokeCallback()
#7 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(676): Revolt\EventLoop\Driver\StreamSelectDriver->dispatch()
#8 /opt/web/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(96): Revolt\EventLoop\Internal\AbstractDriver->tick()
#9 [internal function]: Revolt\EventLoop\Internal\AbstractDriver->run()
#10 /opt/web/vendor/revolt/event-loop/src/EventLoop/Suspension.php(95): Fiber->resume()
#11 /opt/web/vendor/amphp/amp/lib/functions.php(81): Revolt\EventLoop\Suspension->suspend()
#12 /opt/web/server.php(346): Amp\trapSignal()
#13 {main}
  thrown in /opt/web/vendor/amphp/amp/lib/Internal/FutureState.php on line 38
Segmentation fault
```

**Comment by blaxxun-boop** [comment]
Hey,

I've pushed a fix for this, thanks.

Cheers.
